import assert from "node:assert/strict";
import test from "node:test";
import {
  ALL_ATTRIBUTE_KEYS,
  COMMON_SPAN_ATTRIBUTES,
  RESOURCE_ATTRIBUTES,
} from "../src/semconv/attributes.ts";

const documentedAttributeKeys = [
  "deployment.environment.name",
  "error.type",
  "event.category",
  "event.name",
  "gen_ai.agent.id",
  "gen_ai.agent.name",
  "gen_ai.agent.version",
  "gen_ai.conversation.id",
  "gen_ai.input.messages",
  "gen_ai.operation.name",
  "gen_ai.output.messages",
  "gen_ai.provider.name",
  "gen_ai.request.max_tokens",
  "gen_ai.request.model",
  "gen_ai.request.temperature",
  "gen_ai.response.finish_reasons",
  "gen_ai.response.id",
  "gen_ai.response.model",
  "gen_ai.tool.call.arguments",
  "gen_ai.tool.call.id",
  "gen_ai.tool.call.result",
  "gen_ai.tool.name",
  "gen_ai.tool.type",
  "gen_ai.usage.cache_creation.input_tokens",
  "gen_ai.usage.cache_read.input_tokens",
  "gen_ai.usage.input_tokens",
  "gen_ai.usage.output_tokens",
  "gen_ai.usage.reasoning.output_tokens",
  "observme.capture.prompts",
  "observme.capture.responses",
  "observme.capture.tool_arguments",
  "observme.environment",
  "observme.evicted",
  "observme.instance.id",
  "observme.original_length",
  "observme.redaction.enabled",
  "observme.replayed",
  "observme.semconv.version",
  "observme.tenant.id",
  "observme.truncated",
  "observme.version",
  "pi.agent.child.count",
  "pi.agent.child.id",
  "pi.agent.child.status",
  "pi.agent.children.active",
  "pi.agent.depth",
  "pi.agent.failure.propagated",
  "pi.agent.id",
  "pi.agent.join.status",
  "pi.agent.parent_id",
  "pi.agent.role",
  "pi.agent.root_id",
  "pi.agent.run.id",
  "pi.agent.run.index",
  "pi.agent.run.prompt.hash",
  "pi.agent.run.prompt.length",
  "pi.agent.run.source",
  "pi.agent.spawn.command.hash",
  "pi.agent.spawn.id",
  "pi.agent.spawn.outcome",
  "pi.agent.spawn.reason",
  "pi.agent.spawn.tool_call_id",
  "pi.agent.spawn.trace_context_propagated",
  "pi.agent.spawn.type",
  "pi.agent.wait.reason",
  "pi.bash.cancelled",
  "pi.bash.command.hash",
  "pi.bash.command.redacted",
  "pi.bash.exclude_from_context",
  "pi.bash.exit_code",
  "pi.bash.full_output_path_present",
  "pi.bash.output.hash",
  "pi.bash.output.redacted",
  "pi.bash.output.size",
  "pi.bash.truncated",
  "pi.branch.common_ancestor_id",
  "pi.branch.from_hook",
  "pi.branch.from_id",
  "pi.branch.modified_files_count",
  "pi.branch.path_hash",
  "pi.branch.read_files_count",
  "pi.branch.summary.hash",
  "pi.branch.summary.length",
  "pi.branch.to_id",
  "pi.compaction.first_kept_entry_id",
  "pi.compaction.from_hook",
  "pi.compaction.modified_files_count",
  "pi.compaction.read_files_count",
  "pi.compaction.reason",
  "pi.compaction.summary.hash",
  "pi.compaction.summary.length",
  "pi.compaction.tokens_before",
  "pi.compaction.will_retry",
  "pi.cwd.basename",
  "pi.cwd.hash",
  "pi.entry.id",
  "pi.entry.parent_id",
  "pi.entry.type",
  "pi.leaf.id",
  "pi.llm.api",
  "pi.llm.cost.cache_read_usd",
  "pi.llm.cost.cache_write_usd",
  "pi.llm.cost.input_usd",
  "pi.llm.cost.output_usd",
  "pi.llm.cost.total_usd",
  "pi.llm.error_message_hash",
  "pi.llm.prompt.redacted",
  "pi.llm.request.input_chars",
  "pi.llm.request.message_count",
  "pi.llm.request.thinking_level",
  "pi.llm.request.tool_schema_count",
  "pi.llm.response.redacted",
  "pi.llm.stop_reason",
  "pi.llm.thinking.redacted",
  "pi.llm.usage.cache_write_1h_tokens",
  "pi.llm.usage.total_tokens",
  "pi.model.id.current",
  "pi.model.provider.current",
  "pi.project.name",
  "pi.session.id",
  "pi.tool.arguments.hash",
  "pi.tool.arguments.redacted",
  "pi.tool.arguments.size",
  "pi.tool.call.id",
  "pi.tool.category",
  "pi.tool.error",
  "pi.tool.error_class",
  "pi.tool.name",
  "pi.tool.result.hash",
  "pi.tool.result.redacted",
  "pi.tool.result.size",
  "pi.tool.success",
  "pi.turn.branch_path_hash",
  "pi.turn.id",
  "pi.turn.index",
  "pi.turn.user_message.hash",
  "pi.turn.user_message.image_count",
  "pi.turn.user_message.length",
  "pi.user.hash",
  "pi.workflow.id",
  "pi.workflow.root_agent_id",
  "service.instance.id",
  "service.name",
  "service.namespace",
  "service.version",
  "severity",
  "span_id",
  "telemetry.sdk.name",
  "trace_id",
].sort((left, right) => left.localeCompare(right));

test("exports every attribute key documented in semantic convention sections 2-3, 5-11, and 14", () => {
  assert.deepEqual(ALL_ATTRIBUTE_KEYS, documentedAttributeKeys);
});

test("exports required resource and operational attributes", () => {
  assert.equal(RESOURCE_ATTRIBUTES.OBSERVME_TENANT_ID, "observme.tenant.id");
  assert.equal(COMMON_SPAN_ATTRIBUTES.OBSERVME_REPLAYED, "observme.replayed");
  assert.equal(COMMON_SPAN_ATTRIBUTES.OBSERVME_EVICTED, "observme.evicted");
  assert.equal(COMMON_SPAN_ATTRIBUTES.OBSERVME_TRUNCATED, "observme.truncated");
  assert.equal(COMMON_SPAN_ATTRIBUTES.OBSERVME_ORIGINAL_LENGTH, "observme.original_length");
});

test("attribute key exports are unique and stay out of the bare agent namespace", () => {
  assert.equal(new Set(ALL_ATTRIBUTE_KEYS).size, ALL_ATTRIBUTE_KEYS.length);
  assert.equal(ALL_ATTRIBUTE_KEYS.some(key => key.startsWith("agent.")), false);
});
